@HostAddress = http://localhost:5162

GET {{HostAddress}}/required-param
Accept: application/json

###

GET {{HostAddress}}/minlength-param
Accept: application/json

###

GET {{HostAddress}}/minlength-param?name=Bill
Accept: application/json

###

GET {{HostAddress}}/path-param/Bill
Accept: application/json

###

GET {{HostAddress}}/int-path-param/1
Accept: application/json
