extends: spectral:oas
rules:
  info-contact: off
  info-description: off
  oas3-api-servers: off

  success-response:
    description: All operations should have a success response.
    message: Operation is missing a success response.
    severity: warn
    given: $.paths.*.*.responses
    then:
      function: schema
      functionOptions:
        schema:
          anyOf:
            - required: ["200"]
            - required: ["201"]
            - required: ["204"]

  parameter-description:
    description: All parameters should have a description
    message: Parameter is missing a description.
    severity: warn
    given: $.paths.*.*.parameters[*]
    then:
      field: description
      function: truthy
