@HostAddress = http://localhost:5180

GET {{HostAddress}}/foo
Accept: application/json

###

GET {{HostAddress}}/bar
Accept: application/json

###

GET {{HostAddress}}/baz
Accept: application/json

###